import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Thomas Romero Portfolio</title>
        <meta name="description" content="Generated by created..."></meta>
        <link rel="icon" href="./favicon.ico"></link>
      </Head>

      <main>
        <section className="ming-h-screen">
          <nav>
            <h1>Thomas Romero</h1>
            <ul>
              <li>
                <BsFillMoonStarsFill />
              </li>
              <li>
                <a href="#">Resume</a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
// 12:10
